name: Actionfiles tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  run-project-builds:
    name: Run project builds
    uses: ./.github/workflows/reusable-test-projects.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
    secrets: inherit
