name: Actionfiles tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  run-compile-crc:
    name: Compile crc
    uses: ./.github/workflows/reusable-compile-project.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      out-name: "crc"
      actionfile: "projects/crc.md"
    secrets: inherit

  run-compile-macadam:
    name: Compile macadam
    uses: ./.github/workflows/reusable-compile-project.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      out-name: "macadam"
      actionfile: "projects/macadam.md"
    secrets: inherit

  run-compile-gvproxy:
    name: Compile gvproxy
    uses: ./.github/workflows/reusable-compile-project.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      out-name: "gvproxy"
      actionfile: "projects/gvproxy.md"
    secrets: inherit

